"""Initial schema with report indexes

Revision ID: fa2648bb01d7
Revises: 
Create Date: 2025-05-04 16:50:33.927677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa2648bb01d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_session', schema=None) as batch_op:
        batch_op.drop_index('ix_course_session_course_id')
        batch_op.drop_index('ix_course_session_date')
        batch_op.drop_index('ix_course_session_instructor_id')
        batch_op.drop_index('ix_course_session_room_id')
        batch_op.create_index('ix_cs_course', ['course_id'], unique=False)
        batch_op.create_index('ix_cs_course_date', ['course_id', 'date'], unique=False)
        batch_op.create_index('ix_cs_instructor', ['instructor_id'], unique=False)
        batch_op.create_index('ix_cs_room', ['room_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_session', schema=None) as batch_op:
        batch_op.drop_index('ix_cs_room')
        batch_op.drop_index('ix_cs_instructor')
        batch_op.drop_index('ix_cs_course_date')
        batch_op.drop_index('ix_cs_course')
        batch_op.create_index('ix_course_session_room_id', ['room_id'], unique=False)
        batch_op.create_index('ix_course_session_instructor_id', ['instructor_id'], unique=False)
        batch_op.create_index('ix_course_session_date', ['date'], unique=False)
        batch_op.create_index('ix_course_session_course_id', ['course_id'], unique=False)

    # ### end Alembic commands ###
